# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: mfo
  password: mfo
  host: db
  port: 5432
  database: gw_operator
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: gw-operator_test
  <<: *defaults

Staging:
  database: gw-operator_staging
  poolsize: 100
  <<: *defaults

Production:
  database: gw-operator_production
  poolsize: 100
  <<: *defaults
